# Generated by Django 5.0.14 on 2026-02-26 21:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="amount"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                            ("paypal", "PayPal"),
                            ("stripe", "Stripe"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cash_on_delivery", "Cash on Delivery"),
                        ],
                        default="stripe",
                        max_length=30,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                        verbose_name="status",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="External payment provider transaction ID",
                        max_length=255,
                        verbose_name="transaction ID",
                    ),
                ),
                (
                    "payment_intent_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stripe Payment Intent ID",
                        max_length=255,
                        verbose_name="payment intent ID",
                    ),
                ),
                (
                    "charge_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe Charge ID",
                        max_length=255,
                        verbose_name="charge ID",
                    ),
                ),
                (
                    "card_last_four",
                    models.CharField(
                        blank=True, max_length=4, verbose_name="card last four"
                    ),
                ),
                (
                    "card_brand",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="card brand"
                    ),
                ),
                (
                    "billing_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="billing email"
                    ),
                ),
                (
                    "billing_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="billing name"
                    ),
                ),
                (
                    "refunded_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="refunded amount",
                    ),
                ),
                (
                    "refund_reason",
                    models.TextField(blank=True, verbose_name="refund reason"),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="error code"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="error message"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="description"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional payment metadata from provider",
                        verbose_name="metadata",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment",
                "verbose_name_plural": "payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("debug", "Debug"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="level",
                    ),
                ),
                ("event", models.CharField(max_length=100, verbose_name="event")),
                ("message", models.TextField(verbose_name="message")),
                (
                    "data",
                    models.JSONField(blank=True, default=dict, verbose_name="data"),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="payments.payment",
                        verbose_name="payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment log",
                "verbose_name_plural": "payment logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last updated",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="amount"
                    ),
                ),
                ("reason", models.TextField(verbose_name="reason")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "refund_transaction_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="refund transaction ID"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="processed at"
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="payments.payment",
                        verbose_name="payment",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_refunds",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="processed by",
                    ),
                ),
            ],
            options={
                "verbose_name": "refund",
                "verbose_name_plural": "refunds",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["order", "status"], name="payments_pa_order_i_a76289_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["transaction_id"], name="payments_pa_transac_8e9d99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_intent_id"], name="payments_pa_payment_7ccbf1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["user", "status"], name="payments_pa_user_id_01767a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["created_at"], name="payments_pa_created_b8a300_idx"
            ),
        ),
    ]
